import "./globals.css";
import { Inter, Imprima, Abel, Cairo } from "next/font/google";
import { Metadata } from "next";

const imprima = Cairo({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OJII3",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={imprima.className}>{children}</body>
    </html>
  );
}
